API_KEY = 'eAwPLgVrNdnmOaq2lZrsO86gbDVgqD2VUNfJe9Y72uIPr82HZ74VPWK0cvKAItz'
BASE_URL = 'https://ap-south-1.aws.data.mongodb-api.com/app/data-qqelg/endpoint/data/v1'
DATA_SOURCE = 'Analytics'
DATABASE_NAME = 'sample_weatherdata'
COLLECTION_NAME = 'data'